-- QUERIES

-- 1. JOIN
SELECT s.STUDENT_NAME, m.MODULE_NAME, t.TEACHER_NAME
FROM Enrolment e
JOIN Student s ON e.STUDENT_ID = s.STUDENT_ID
JOIN Module m ON e.MODULE_ID = m.MODULE_ID
JOIN Teacher t ON m.TEACHER_ID = t.TEACHER_ID;

-- 2. COUNT
SELECT t.TEACHER_NAME, COUNT(c.CLASS_ID) AS TOTAL_CLASSES
FROM Teacher t
LEFT JOIN Module m ON t.TEACHER_ID = m.TEACHER_ID
LEFT JOIN Class c ON m.MODULE_ID = c.MODULE_ID
GROUP BY t.TEACHER_NAME;

-- 3. SUM
SELECT c.CLASS_ID, SUM(cm.CLASS_MATERIAL_QUANTITY) AS TOTAL_MATERIAL
FROM ClassMaterial cm
JOIN Class c ON cm.CLASS_ID = c.CLASS_ID
GROUP BY c.CLASS_ID;

-- 4. NESTED QUERY
SELECT STUDENT_ID, STUDENT_NAME
FROM Student
WHERE STUDENT_ID IN (
  SELECT STUDENT_ID
  FROM Payment
  GROUP BY STUDENT_ID
  HAVING SUM(PAYMENT_AMOUNT) >
  (SELECT AVG(PAYMENT_AMOUNT) FROM Payment)
);
