-- SCHEMA: CREATE TABLES

CREATE TABLE Student (
  STUDENT_ID VARCHAR2(20) PRIMARY KEY,
  STUDENT_NAME VARCHAR2(100),
  STUDENT_AGE NUMBER,
  STUDENT_CONTACT_NO VARCHAR2(20),
  STUDENT_EMAIL VARCHAR2(100)
);

CREATE TABLE Teacher (
  TEACHER_ID VARCHAR2(20) PRIMARY KEY,
  TEACHER_NAME VARCHAR2(100),
  TEACHER_CONTACT_NO VARCHAR2(20),
  TEACHER_EMAIL VARCHAR2(100)
);

CREATE TABLE Supplier (
  SUPPLIER_ID VARCHAR2(20) PRIMARY KEY,
  SUPPLIER_NAME VARCHAR2(100),
  SUPPLIER_ADDRESS VARCHAR2(200)
);

CREATE TABLE Module (
  MODULE_ID VARCHAR2(20) PRIMARY KEY,
  MODULE_NAME VARCHAR2(100),
  TEACHER_ID VARCHAR2(20),
  FOREIGN KEY (TEACHER_ID) REFERENCES Teacher(TEACHER_ID)
);

CREATE TABLE Class (
  CLASS_ID VARCHAR2(20) PRIMARY KEY,
  CLASS_DAY VARCHAR2(20),
  CLASS_TIME VARCHAR2(20),
  MODULE_ID VARCHAR2(20),
  FOREIGN KEY (MODULE_ID) REFERENCES Module(MODULE_ID)
);

CREATE TABLE Payment (
  PAYMENT_ID VARCHAR2(20) PRIMARY KEY,
  STUDENT_ID VARCHAR2(20) NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  PAYMENT_METHOD VARCHAR2(50) NOT NULL,
  PAYMENT_AMOUNT NUMBER(10,2) NOT NULL,
  FOREIGN KEY (STUDENT_ID) REFERENCES Student(STUDENT_ID)
);

CREATE TABLE Enrolment (
  ENROLMENT_ID VARCHAR2(20) PRIMARY KEY,
  MODULE_ID VARCHAR2(20),
  STUDENT_ID VARCHAR2(20),
  ENROLLMENT_DATE DATE,
  FOREIGN KEY (MODULE_ID) REFERENCES Module(MODULE_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES Student(STUDENT_ID)
);

CREATE TABLE Material (
  MATERIAL_ID VARCHAR2(20) PRIMARY KEY,
  MATERIAL_NAME VARCHAR2(100),
  MATERIAL_AMOUNT NUMBER,
  MATERIAL_UNIT VARCHAR2(20),
  SUPPLIER_ID VARCHAR2(20),
  FOREIGN KEY (SUPPLIER_ID) REFERENCES Supplier(SUPPLIER_ID)
);

CREATE TABLE Equipment (
  EQUIPMENT_ID VARCHAR2(20) PRIMARY KEY,
  EQUIPMENT_NAME VARCHAR2(100),
  EQUIPMENT_AMOUNT NUMBER,
  SUPPLIER_ID VARCHAR2(20),
  FOREIGN KEY (SUPPLIER_ID) REFERENCES Supplier(SUPPLIER_ID)
);

CREATE TABLE ClassMaterial (
  CLASSMATERIAL_ID VARCHAR2(20) PRIMARY KEY,
  CLASS_ID VARCHAR2(20),
  MATERIAL_ID VARCHAR2(20),
  CLASS_MATERIAL_QUANTITY NUMBER,
  FOREIGN KEY (CLASS_ID) REFERENCES Class(CLASS_ID),
  FOREIGN KEY (MATERIAL_ID) REFERENCES Material(MATERIAL_ID)
);

CREATE TABLE ClassEquipment (
  CLASSEQUIPMENT_ID VARCHAR2(20) PRIMARY KEY,
  CLASS_ID VARCHAR2(20),
  EQUIPMENT_ID VARCHAR2(20),
  CLASS_EQUIPMENT_QUANTITY NUMBER,
  FOREIGN KEY (CLASS_ID) REFERENCES Class(CLASS_ID),
  FOREIGN KEY (EQUIPMENT_ID) REFERENCES Equipment(EQUIPMENT_ID)
);
